export const ADDACTIVITY = "ADDACTIVITY"
export const ADDGOODS = "ADDGOODS"
export const TABHIDDEN = 'TABHIDDEN'
export const PRODUCTINFO = 'PRODUCTINFO'
export const SELECTTAB = 'SELECTTAB'
export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_THIS_PRODUCT = 'UPDATE_THIS_PRODUCT'
